language: node_js

os:
 - linux
 - osx

# Use Java 8
osx_image: xcode9.3

node_js:
  - '10'
  - '6'

matrix:
  exclude:
    - os: osx
      node_js: '10'
    - os: linux
      node_js: '6'

# safelist
branches:
  only:
    - master
    - mono-repo

cache:
  yarn: true
  directories:
    - $HOME/.m2

before_install:
  # On Mac OS, maven builds fail with a "Non-resolvable parent POM" error.
  # The fix is to copy a basic maven settings.xml file into the ~/.m2 folder
  # https://stackoverflow.com/a/36982050/1211524
  - if [ $TRAVIS_OS_NAME = "osx" ]; then cp .travis-settings.xml ~/.m2/settings.xml; fi
  #Install yarn version 1.10 by downloading its install script and executing it in bash
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  # For a cron job on travis, test the latest commit on the compiler submodule branch.
  # Disables tests ensuring the submodule is on a tagged commit.
  # Move the submodule pointer to the latest master branch commit.
  # Pipe the latest commit output through cat to log it to the console for debugging
  - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then
      export COMPILER_NIGHTLY=1;
      cd compiler && git checkout master && git pull origin master && git log -1 | cat;
      cd ..;
    fi

before_script: yarn run build

script: yarn test
