language: node_js
node_js:
- '8'
- '6'
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: npm
  email: chadkillingsworth@gmail.com
  on:
    node: '6'
    branch: master
  api_key:
    secure: X3AymiFDe6mH/JGlanoyGixthoWaOv5bGDCQ0Pco3nwTu9BDHEWbhhEdB+TshwKEVWGaVWfaaIDFiKIDBSUcL4xHrHq/VIEu63XH1UQv0KHg6ViSN0SLSJVNUiw61RhGD7S2FBmjTmsgmUzN+NSiNwEH11IlKbdo+tWkerVT1qPI4PpR9xPXvXQjC0kqBT1Khcf9+bkYCpDcE7huopuH6ilDcXKqsXHgad/muJ7mwz+pnZQfUzhj2dmibRWTUnw/E1NoOKQe0F2S9s7wk0cB2nNGrxFc13Vacv9OVvVwosY324QYXTRviILosa9ortvld+ZKAG+hGiwcx/21RO3bR3PKkKrZmjmi6fCrKymX9hk16XFfJbaZBTKVNs4tkmgrU1ftrrI6jqDoqAHyvSvid8rTNs6MBOKJixffjHVN2xSLCJL+ZLzgrUHL159NFJdCnRzTySGu/WLUvY42v+CWkDmccas3R2tfksZS1Qx2wGLF053acbY95i5efxZ9/uFBiWO6/N/b0B4tBXWL6S2OsIfgF2+vug6bN222MIZgvZFRjYLbhV2Zhy2Km6DYEWdDrhZuWMV3Wv1DIW1k5n0zfQV506BD572OJY3G6MZ2cxweGutLD67bcfhDjpPtMl+6bAyR0woKNG8Q5sBgAtFAZZ/kgK5IfL41rC6J6BHTsS8=
