version: 1.0.{build}

image: Visual Studio 2019

clone_depth: 50

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  PATH: C:\Program Files (x86)\Apache\Maven\bin;C:\Program Files\Java\jdk11\bin;%PATH%

branches:
  only:
    - master

cache:
  - '%USERPROFILE%\.m2'
  - '%LOCALAPPDATA%\yarn\cache'

install:
  - "@echo on"
  # Setup windows SDK build environment variables - Graal on windows only supports 64bit architectures
  - '"\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=amd64'
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "Appveyor"
  - git submodule update --init --recursive
  # Install expected versions of node and yarn
  - choco install nodejs --version 12.4.0
  - choco install yarn
  - yarn install --colors=always
  - IF "%COMPILER_NIGHTLY%" == "1" CD compiler
  - IF "%COMPILER_NIGHTLY%" == "1" git checkout master
  - IF "%COMPILER_NIGHTLY%" == "1" git pull origin master
  - IF "%COMPILER_NIGHTLY%" == "1" git log -1 | cat
  - IF "%COMPILER_NIGHTLY%" == "1" CD ..

build_script:
  - "@echo on"
  - java -version
  - node ./build-scripts/build_compiler.js --colors=always
  - yarn workspaces run build

test_script:
  - "echo on"
  - yarn workspaces run test --colors
  - node_modules/.bin/mocha --colors

deploy_script:
  - node build-scripts/add-os-restrictions.js
  - IF "%COMPILER_NIGHTLY%" == "1" node build-scripts/create-nightly-version.js
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" IF "%APPVEYOR_REPO_BRANCH%" == "master" node build-scripts/lerna-publish.js publish-travis --npm-client "%APPVEYOR_BUILD_FOLDER%/build-scripts/npm-client.js" --ignore-changes "**/*" --force-publish="*" --yes
